nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: ./bundles/@yarnpkg/plugin-workspace-lockfile.js
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js
  - checksum: d1b1142e8acf30b61023df541d3405617356e65ca4b02fa949a31ab1492e70b9b627456fdcb2fba670ebfcbb7d7fc7b5f99cc62360599bf13c2295fbbe96b5e3
    path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: "https://github.com/MaintainX/yarn-plugin-aws-codeartifact/releases/download/v0.22.0-mx/plugin-aws-codeartifact.js"
  - checksum: 627893516485148067c93dbcad672faf71332596b318b10aabf48b7fbdb8d620fedaf1004b922dd08f77c7d0b688a9e6f722d604f2bd22b8196baf2d3d378566
    path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/96ffd15fdb25310613f003a2c258dfd73eaa36a1/index.js"

workspaceLockfileLoggingLevel: info

yarnPath: .yarn/releases/yarn-4.12.0.cjs
