nodeLinker: node-modules

plugins:
  - checksum: ae106bdf682b7af460d16e6045caf409b9b0b6dcc53c221b3b066f9c5cc5ec5b04a90595ab8738a9a5ed64688064cc15cfbe24c69a010068ac24ecf34607dff1
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
