nodeLinker: node-modules

plugins:
  - checksum: ff109de007cef2aac16e9741ce2be133f1f55be014245072b9067ae7c870a2b6ede2bdafb01c11058b1f8e9dbb66abfbbcd1d4013a5ec23458f08afd67a50d0f
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
