nodeLinker: node-modules
nmHoistingLimits: workspaces
workspaceLockfileLoggingLevel: info

plugins:
  - path: ./bundles/@yarnpkg/plugin-workspace-lockfile.js
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
