nodeLinker: node-modules

plugins:
  - checksum: 26f769775d17c325e5150d7f9d95984be61f516326ff50e872314046d6356cbe91aeeb929f6ebb5ea4622c36dd43fa8f2f7ba20fb11a04642dfa04bda9663b4f
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
