nodeLinker: node-modules

plugins:
  - checksum: fd285ab84b6c806dc529b7d4ebe063789fa754b6dcc402719eb7a861845a99c42b8da2a9f821d7171c647755cd1834cec74a227cb4f204cfeea435c919d733f9
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
