nodeLinker: node-modules

plugins:
  - checksum: 02aebe14418f1eae925247e4b7879620146de83fefb60dc9109733bc0dd0ae71b7835949fd2fff62224f818adf7546de4133ffcefad0f982a93a08afbd1d3d3d
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
