nodeLinker: node-modules

plugins:
  - checksum: 2a337274676e734024a0cf6b7306f463b11bef48d35ca5c65c6ed7c708804411fac2b02ed22a57ea0403defee1c01ddb1be6176949250c7bd9fd3babdcd031db
    path: .yarn/plugins/@yarnpkg/plugin-workspace-lockfile.cjs
    spec: bundles/@yarnpkg/plugin-workspace-lockfile.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
